name=input("Enter Name:")
print("User Name -",name)
age=input("Enter Age:")
print("User Age -",age)
roll_no=input("Enter Roll_number:")
print("User Roll_number -",roll_no)
Phone_no=input("Enter Mobile_Number:")
print("User Mobile_Numer -",Phone_no)
print("User Details")
print(name , age , roll_no , Phone_no )